apiVersion: v1
kind: Namespace
metadata:
  name:  databases
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/databases/rabbitmq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-claim
  namespace: databases
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi