apiVersion: v1
kind: Namespace
metadata:
  name:  databases
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-master
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/databases/redis/master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-claim-master
  namespace: databases
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-replica
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/databases/redis/replica"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-claim-replica
  namespace: databases
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi